---
name: Hyper 2000 Solarflow Control
version: "0.1.4"
slug: solarflow-control
description: Hyper 2000 Solarflow Control is a Home Assistant add-on that allows you to control your solar power system.
url: "https://github.com/atrox06/addon-solarflow-control"
init: false
panel_icon: mdi:solar-power-variant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - share:rw
options:
  dtu_type: "None"
  use_cloud: true
  grid_charge: true
  smartmeter_type: "Smartmeter"
  full_charge_interval: 32
  control_bypass: true
  control_soc: false
  battery_low: 5
  battery_high: 100
  cloud_web_user: ""
  cloud_web_password: ""
  web_token_url: "https://app.zendure.tech/eu/auth/app/token"
  web_device_list_url: "https://app.zendure.tech/eu/productModule/device/queryDeviceListByConsumerId"
  cloud_mqtt_port: 1883
  cloud_mqtt_host: "mqtteu.zen-iot.com"
  cloud_mqtt_user: "zenApp"
  cloud_mqtt_password: ""
  roofsolar_base_topic: "roofsolar"
  mqtt_host: ""
  mqtt_user: ""
  mqtt_password: ""
  dtu_base_topic: "solar"
  inverter_max_power: 2000
  opendtu_inverter_serial: ""
  ahoydtu_inverter_id: "0"
  sm_generic_base_topic: ""
  sm_generic_cur_accessor: ""
  sm_generic_total_accessor: ""
  sm_rapid_change_diff: 500
  sm_zero_offset: 20
  sm_scaling_factor: 1
  sm_shelly3em_base_topic: "shellies/shellyem3/"
  min_grid_charge_power: 100
  max_grid_charge_power: 1200
  min_charge_power: 125
  max_discharge_power: 1200
  min_discharge_power: 125
  limit_inverter: true
  max_inverter_limit: 800
  min_inverter_limit: 10
  discharge_during_daytime: false
  sunrise_offset: 60
  sunset_offset: 60
schema:
  dtu_type: list(OpenDTU|AhoyDTU|None)
  use_cloud: bool
  grid_charge: bool
  smartmeter_type: list(Smartmeter|PowerOpti|ShellyEM3)
  product_id: str
  device_id: str
  full_charge_interval: int
  control_bypass: bool
  control_soc: bool
  battery_low: int
  battery_high: int
  cloud_web_user: str?
  cloud_web_password: password?
  web_token_url: str
  web_device_list_url: str
  cloud_mqtt_port: port?
  cloud_mqtt_host: str
  cloud_mqtt_user: str?
  cloud_mqtt_password: password?
  roofsolar_base_topic: str
  mqtt_host: str
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: password?
  dtu_base_topic: str
  sf_inverter_channels: str
  inverter_max_power: int?
  opendtu_inverter_serial: str?
  ahoydtu_inverter_id: int?
  sm_rapid_change_diff: int?
  sm_zero_offset: int?
  sm_scaling_factor: int?
  sm_generic_base_topic: str?
  sm_generic_cur_accessor: str?
  sm_generic_total_accessor: str?
  sm_poweropti_user: str?
  sm_poweropti_password: password?
  sm_shelly3em_base_topic: str?
  min_grid_charge_power: int?
  max_grid_charge_power: int?
  min_charge_power: int?
  max_discharge_power: int?
  min_discharge_power: int?
  limit_inverter: bool?
  max_inverter_limit: int?
  min_inverter_limit: int?
  discharge_during_daytime: bool?
  latitude: float?
  longitude: float?
  sunrise_offset: int?
  sunset_offset: int?
